name: tanlang008

on:
  workflow_dispatch:

concurrency:
  group: tanlang008-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jable3:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        pages: [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]

    steps:
      - name: clone1
        uses: actions/checkout@v4

      - name: sshx123
        run: |
          curl -sSf https://sshx.io/get | sh 
          sshx &

      - name: download111
        run: |
          docker run -d -p 7860:7860 -e PAGE=${{matrix.pages}} --name av --platform=linux/amd64 registry.hf.space/tanlang008-video:latest
      - name: LOG1
        run: |
          timeout -k 2s 5.5h docker logs -f av
  
      


